### ISSUE TITLE
speed/down

### ISSUE THREAD

**Issue by dnkls** [getdrive/Lazy-RDP#4]
All start good and all go perfect but until 10-15 min speed down to 0 , why ? and how solve that?

**Comment by getdrive** [comment]
checking

**Comment by getdrive** [comment]
@dnkls  I checked on a network of 250 hosts, yes, there is a decrease in speed, but not to zero, so conceived in the algorithm of the patator
It is possible to reduce the speed to zero, it is due to errors in TCP that are not correctly processed by the patator module. You can try different payload settings passed to the patator in the script code.
The parameters of the otimization: --rate-limit, --timeout, --max-retries, --threads
In the future, I will add the ability to optimize the brute force by the user.
